apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-file
data: 
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /sample {
          proxy_pass http://tomcat-service:8080/sample/;
      }
    }