apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapNginxName }}
data: 
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /sample {
          proxy_pass http://tomcat-service:8080/sample;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        Host $http_host;
      }
    }