# simple-app-tomcat-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-tomcat
  labels:
    app: simple-app-tomcat-pod
spec:
  replicas: {{ .Values.replicaCountTomcat }}
  selector:
    matchLabels:
      app: simple-app-tomcat-pod
  template:
    metadata:
      labels:
        app: simple-app-tomcat-pod
    spec:
      containers:
        - name: simple-app-tomcat-container
          image: "{{ .Values.imageTomact.repository }}:{{ .Values.imageTomact.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data
              mountPath: /usr/local/tomcat/webapps/
      initContainers:
        - name: download-container
          image: busybox
          command: ['wget', '{{ .Values.sourceURL }}', '-O', '/source/sample.war']
          volumeMounts:
            - name: shared-data
              mountPath: /source
      volumes:
        - name: shared-data
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-nginx
  labels:
    app: proxy-nginx-pod
spec:
  replicas: {{ .Values.replicaCountNginx }}
  selector:
    matchLabels:
      app: proxy-nginx-pod
  template:
    metadata:
      labels:
        app: proxy-nginx-pod
    spec:
      containers:
        - name: proxy-nginx-container
          image: "{{ .Values.imageNginx.repository }}:{{ .Values.imageNginx.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-file
