apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: simple-app-tomcat-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort