apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    {{ .Values.labelsTomcat.key }}: {{ .Values.labelsTomcat.value }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
