apiVersion: v1
kind: Pod
metadata:
  name: simple-app-tomcat
  labels:
    app: simple-app-tomcat-pod
spec:
  containers:
    - name: simple-app-tomcat-container
      image: tomcat
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shared-data
          mountPath: /usr/local/tomcat/webapps/

  initContainers:
    - name: download-container
      image: busybox
      command: ['wget', 'https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war', '-O', '/source/sample.war']
      volumeMounts:
        - name: shared-data
          mountPath: /source
  
  volumes:
    - name: shared-data
      emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-file
data: 
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /sample {
          proxy_pass http://tomcat-service:8080/sample/;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy-nginx
  labels:
    app: proxy-nginx-pod
spec:
  containers:
    - name: proxy-nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf-file
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: simple-app-tomcat-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080