version: '3'
services:
  python-app:
    image: python-app

  proxy:
    volumes:
      - /path/to/mount:/etc/nginx/conf.d/default.conf

  fluentd:
    volumes:
      - /path/to/mount:/fluentd/etc/fluent.conf