version: '3'

services:
  python-app:
    build:
      context: python-app
    container_name: python-app
    hostname: python-app
    networks:
      - network-app
    ports:
      - "5000:5000"
    depends_on:
      - cache
      - database
      - fluentd
    cpu_percent: 10
    mem_limit: 128m
    links: 
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: python-app
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  proxy:
    image: nginx
    container_name: proxy
    networks:
      - network-app
    ports:
      - "80:80"
    depends_on:
      - python-app
    cpu_percent: 10
    mem_limit: 128m
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: journald
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  cache:
    image: redis
    container_name: cache
    networks:
      - network-app
    cpu_percent: 10
    mem_limit: 128m
    logging:
      driver: journald
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3

  database:
    image: postgres
    container_name: database
    networks:
      - network-app
    cpu_percent: 10
    mem_limit: 128m
    logging:
      driver: journald
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 10s
      retries: 3

  fluentd:
    image: fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - network-app
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    logging:
      driver: journald

networks:
  network-app:
    driver: bridge