version: '3'

services:
  python-app:
    build:
      context: python-app
    container_name: python-app
    hostname: python-app
    networks:
      - frontend
      - backend
    ports:
      - "${PYTHON_APP_PORT}:5000"
    depends_on:
      - cache
      - database
      - fluentd
    cpu_percent: ${PYTHON_CPU_PERCENT}
    mem_limit: ${PYTHON_MEM_LIMIT}
    links: 
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:${FLUENTD_PORT}
        tag: python-app
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  proxy:
    image: nginx
    container_name: proxy
    networks:
      - frontend
    ports:
      - "${PROXY_PORT}:80"
    depends_on:
      - python-app
    cpu_percent: ${PROXY_CPU_PERCENT}
    mem_limit: ${PROXY_MEM_LIMIT}
    logging:
      driver: journald
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: curl -sS http://127.0.0.1/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  cache:
    image: redis
    container_name: cache
    networks:
      - backend
    ports:
      - "${CACHE_PORT}:6379"
    cpu_percent: ${CACHE_CPU_PERCENT}
    mem_limit: ${CACHE_MEM_LIMIT}
    logging:
      driver: journald
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3

  database:
    image: postgres
    container_name: database
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    cpu_percent: ${DATABASE_CPU_PERCENT}
    mem_limit: ${DATABASE_MEM_LIMIT}
    logging:
      driver: journald
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 10s
      retries: 3

  fluentd:
    image: fluentd
    container_name: fluentd
    ports:
      - "127.0.0.1:${FLUENTD_PORT}:24224"
      - "127.0.0.1:${FLUENTD_PORT}:24224/udp"
    cpu_percent: ${FLUENTD_CPU_PERCENT}
    mem_limit: ${FLUENTD_MEM_LIMIT}
    networks:
      - frontend
    logging:
      driver: journald
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    healthcheck:
      test: [ "CMD", "nc", "-u", "-z", "-v", "localhost", "24224" ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  frontend:
  backend:
    internal: true
