version: '3'

services:
  python-app:
    container_name: python-app
    build:
      context: python-app
    ports:
      - "5000:5000"
    depends_on:
      - proxy
      - cache
      - database
    cpu_percent: 10
    mem_limit: 128m

  proxy:
    container_name: proxy
    build:
      context: nginx
    ports:
      - "80:80"
    cpu_percent: 10
    mem_limit: 128m

  cache:
    container_name: cache
    image: redis
    cpu_percent: 10
    mem_limit: 128m

  database:
    container_name: database
    image: postgres
    cpu_percent: 10
    mem_limit: 128m