---
# tasks file for ansible-role-provision

- name: Install nginx, openssl, ufw
  ansible.builtin.package:
    name: 
      - nginx
      - openssl
      - ufw
    update_cache: yes
    state: present

# Configure firewall (allow SSH, HTTP, HTTPS)
- name: Allow port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
- name: Allow port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Allow port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
- name: Enable UFW
  community.general.ufw:
    state: enabled

# Add users for sites administration, set ssh keys
- name: Add the user-a
  ansible.builtin.user:
    name: user-a
    shell: /bin/bash
    create_home: true
- name: Create ssh directory
  ansible.builtin.file:
    path: /home/user-a/.ssh
    state: directory
    mode: '0755'
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/user-a-authorized_keys
    dest: /home/user-a/.ssh/authorized_keys
    owner: user-a
    group: user-a
    mode: '0644'
- name: Add the user-a
  ansible.builtin.user:
    name: user-b
    shell: /bin/bash
    create_home: true
- name: Create ssh directory
  ansible.builtin.file:
    path: /home/user-b/.ssh
    state: directory
    mode: '0755'
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/user-a-authorized_keys
    dest: /home/user-b/.ssh/authorized_keys
    owner: user-a
    group: user-a
    mode: '0644'

