name: Deploy to AWS

on:
  pull_request:
    branches:
      - task1-cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::357197750522:role/actionsgithub
          aws-region: eu-central-1
      - name: Build
        run: |
          cd task1/hello
          sam build
      - name: Deploy
        run: |
          cd task1/hello 
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name app-${{github.event.pull_request.number}}          
      - id: geturl
        name: Get app url
        run: |
          url=$(aws cloudformation describe-stacks --stack-name app-${{github.event.pull_request.number}} | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "HelloWorldApi") | .OutputValue')
          echo "url=$url" >> $GITHUB_OUTPUT
      - name: Get current date
        id: date
        run: echo "timenow=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{steps.geturl.outputs.url}} ${{ steps.date.outputs.timenow }}'
            })