name: Deploy to AWS

on:
  pull_request:
    branches:
      - task1-cicd

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION
      - name: build
        run: |
          cd task1/hello
          sam build
      - name: deploy
        run: |
          cd task1/hello 
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          
      - id: geturl
        name: geturl
        run: |
          url=$(aws cloudformation describe-stacks --stack-name sam-app | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "HelloWorldApi") | .OutputValue')
          echo $url >> $GITHUB_OUTPUT
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{steps.geturl.outputs.url}} ${{ github.event.repository.updated_at }}'
            })
