name: Deploy Application

on:
  push:
    branches: [ task1-cicd ]
  pull_request:
    branches: [ task1-cicd ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          # Your deployment script here
