name: Pull Request Environment

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation and pushes

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1          # Replace with your desired region

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Deploy to temporary environment (modify for your deployment tool)
        run: aws s3 cp --recursive build s3://your-bucket-name/$GITHUB_SHA 

      - name: Get deployment URL (modify based on your deployment strategy)
        id: get-url
        run: echo "Deployment URL: https://bucket.s3.$AWS_REGION.amazonaws.com/$GITHUB_SHA" 

      - name: Add comment to pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deployed at ${new Date().toLocaleString()}. See the application here: ${{ steps.get-url.outputs.URL }}`
            })

  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Only run after build-and-deploy job finishes
    if: github.event.action == 'closed' || github.event.action == 'merged'  # Only run on PR close/merge
    steps:
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Destroy temporary environment
        run: aws s3 rm --recursive s3://your-bucket-name/$GITHUB_SHA 
