name: Deploy to AWS

on: 
  pull_request:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        run: |
          echo "hello"

