name: Deploy to AWS

on:
  workflow_dispatch:
  pull_request:
    branches:
      - task1-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Run program
        run: python task1/app.py
